[package]
name = "gnome-steam-icon-watcher"
version = "1.1.0"
edition = "2024"

[dependencies]
procfs = "0.16"
log = "0.4"
env_logger = "0.11"
regex = "1.11.1"
byteorder = "1.5.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
image = "0.25.6"
